
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Dekanat
{

using System;
    using System.Collections.Generic;
    
public partial class Credentials
{

    public int CredentialId { get; set; }

    public int Teacher { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }



    public virtual Teachers Teachers { get; set; }

}

}
