
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Dekanat
{

using System;
    using System.Collections.Generic;
    
public partial class DeletedMarks
{

    public int MarkId { get; set; }

    public int Student { get; set; }

    public int SubjectInfo { get; set; }

    public Nullable<System.DateTime> MarkDate { get; set; }

    public Nullable<int> Mark { get; set; }

    public int MarkType { get; set; }

    public Nullable<int> Status { get; set; }

}

}
