
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Dekanat
{

using System;
    using System.Collections.Generic;
    
public partial class Departments
{

    public Departments()
    {

        this.Courses = new HashSet<Courses>();

        this.Teachers = new HashSet<Teachers>();

    }


    public int DepartmentId { get; set; }

    public string DepartmentName { get; set; }

    public int Institute { get; set; }



    public virtual ICollection<Courses> Courses { get; set; }

    public virtual Institutes Institutes { get; set; }

    public virtual ICollection<Teachers> Teachers { get; set; }

}

}
