
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Dekanat
{

using System;
    using System.Collections.Generic;
    
public partial class SubjectNames
{

    public SubjectNames()
    {

        this.SubjectInfo = new HashSet<SubjectInfo>();

    }


    public int SubjectNameId { get; set; }

    public string SubjectName { get; set; }



    public virtual ICollection<SubjectInfo> SubjectInfo { get; set; }

}

}
