
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Dekanat
{

using System;
    using System.Collections.Generic;
    
public partial class SubjectInfo
{

    public SubjectInfo()
    {

        this.AssociatedSubjects = new HashSet<AssociatedSubjects>();

        this.Marks = new HashSet<Marks>();

    }


    public int SubjectInfoId { get; set; }

    public decimal Credits { get; set; }

    public int QualificationLevel { get; set; }

    public int StudyForm { get; set; }

    public int Course { get; set; }

    public System.DateTime SubjectInfoDate { get; set; }

    public int SubjectName { get; set; }



    public virtual ICollection<AssociatedSubjects> AssociatedSubjects { get; set; }

    public virtual Courses Courses { get; set; }

    public virtual ICollection<Marks> Marks { get; set; }

    public virtual QualificationLevels QualificationLevels { get; set; }

    public virtual StudyForms StudyForms { get; set; }

    public virtual SubjectNames SubjectNames { get; set; }

}

}
