
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Dekanat
{

using System;
    using System.Collections.Generic;
    
public partial class Teachers
{

    public Teachers()
    {

        this.AssociatedSubjects = new HashSet<AssociatedSubjects>();

        this.Credentials = new HashSet<Credentials>();

    }


    public int TeacherId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string MiddleName { get; set; }

    public System.DateTime BirthDate { get; set; }

    public string Address { get; set; }

    public string MobilePhone { get; set; }

    public int Department { get; set; }

    public int AcademicRank { get; set; }

    public bool HasCredential { get; set; }



    public virtual AcademicRanks AcademicRanks { get; set; }

    public virtual ICollection<AssociatedSubjects> AssociatedSubjects { get; set; }

    public virtual ICollection<Credentials> Credentials { get; set; }

    public virtual Departments Departments { get; set; }

}

}
