
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DekanatForTeacher
{

using System;
    using System.Collections.Generic;
    
public partial class Institutes
{

    public Institutes()
    {

        this.Departments = new HashSet<Departments>();

    }


    public int InstituteId { get; set; }

    public string InstituteName { get; set; }

    public string InstituteSName { get; set; }



    public virtual ICollection<Departments> Departments { get; set; }

}

}
