
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DekanatForTeacher
{

using System;
    using System.Collections.Generic;
    
public partial class MarkTypes
{

    public MarkTypes()
    {

        this.Marks = new HashSet<Marks>();

    }


    public int MarkTypeId { get; set; }

    public string MarkTypeName { get; set; }



    public virtual ICollection<Marks> Marks { get; set; }

}

}
